DROP TABLE "aktywnosc";
DROP TABLE "donosy";
DROP TABLE "ministerstwo";
DROP TABLE "myslozbrodnie";
DROP TABLE "obywatel";
DROP TABLE "obywatel_aktywnosc";
DROP TABLE "obywatel_rozmowa";
DROP TABLE "praca";
DROP TABLE "rozmowa";
